### ISSUE TITLE
Teasergruppe

### ISSUE THREAD

**Issue by gewaechshaus** [davidverholen/magento2-teaser#1]
Hallo @davidverholen,

kannst du mir kurz erklären wie die Zuordnung der Blöcke in die Teasergruppe erfolgt? Wird anhand des Namens gemapped?

Beste Grüße
Jan

**Comment by davidverholen** [comment]
Hallo Jan,

einer Teasergruppe können Teaser Items hinzugefügt werden, die dann jeweils einen Block enthalten können. In Version 1.1 funktioniert das noch nicht über das Backend, da dort bestimmte Elemente genutzt werden, die wahrscheinlich erst mit Magento 2.1 released werden. Du müsstest also die Version 1.0 benutzen.

Viele Grüße,
David

**Comment by gewaechshaus** [comment]
Hallo David,

vielen Dank für deine zügige Antwort. Ich klone mir mal die 1.0... Dank dir schonmal ganz herzlich für die Arbeit die du dir gemacht hast - wenn du Hilfe brauchst, sag Bescheid. Ich bin zwar noch relativ am Anfang mit Magento 2, aber bei 1 von Anfang an dabei. 

Viele Grüße
Jan

**Comment by gewaechshaus** [comment]
Evtl. könnte man im nächsten Schritt mal eine Slider Lib inkludieren und das notwendige JS vorbereiten...

**Comment by davidverholen** [comment]
Hi Jan,

das Modul ist eigentlich nur für statische Teaser gedacht. Für große Stage Slider nutzen wir ein anderes Modul (leider nicht open source). Die Module sind zwar vom Aufbau her ziemlich ähnlichm dennoch macht es Sinn, diese inhaltlich zu trennen und auch die Einstellungsmöglichkeiten für die Slider unterscheiden sich noch ein bisschen.

Für Produkt Slider bietet es sich an, das schon vorhandene Product List Widget zu ertweitern um ein Template, dass eine Slider lib einbindet. 

Ich denke, sobald Magento (hoffentlich mit 2.1) die erweiterten UI Components released, werde ich hier auch nochmal weiter arbeiten und das Ganze auch im Backend ein wenig schöner aufbauen ;)

Viele Grüße,
David

**Comment by gewaechshaus** [comment]
Hi David,

vielen Dank für die ausführliche Antwort... Ich baue gerade erstmal den bxSlider auf Templatebasis ein und passe mir deine Templates was an bzw. mache neue dafür. Soll ein klassischer Teaserslider werden mit verschiedenen Inhalten... 

Beste Grüße
Jan
